### ISSUE TITLE
Wrong build version shown in output

### ISSUE THREAD

**Issue by tkatz** [qoomon/maven-branch-versioning-extension#2]
The replacement of slashes in branch names works fine for the build version, nevertheless the wrong version is displayed.

    [INFO] Scanning for projects...
    [INFO] --- maven-branch-versioning-extension:2.6.0 ---
    [INFO] project-name:0.1.0-SNAPSHOT - branch: feature/COM-28-initial-setup - version: feature/COM-28-initial-setup-SNAPSHOT
    [INFO] 

Actual build version is named correctly

    project-name-feature-COM-28-initial-setup-SNAPSHOT-sources.jar

**Comment by qoomon** [comment]
fixed in release v3.1.3 3ec6962
